prod_job:
    stage: deploy
    only:
        - master
    
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$PROD_SSH_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "HOST *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        
    script:
        - bash .gitlab-deploy-prod.sh
        
    environment:
        name: production
        url: https://www.api.shapeai.cf