module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  ignorePatterns: ['node_modules/'],
  extends: ['prettier'],
  rules: {
    'arrow-parens': 0,
    'no-console': 'error',
    'no-underscore-dangle': 0,
    'no-use-before-define': 0,
    'quote-props': 0,
    'no-await-in-loop': 0,
    'max-len': ['warn', { code: 300 }],
    'no-return-assign': ['off'],
    camelcase: 'warn',
    quotes: ['error', 'single', { allowTemplateLiterals: false }],
    'use-isnan': 'error',
    'dot-location': 'warn',
    eqeqeq: 'error',
    'no-alert': 'error',
    'no-eval': 'error',
    'no-useless-escape': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-useless-call': 'error',
    'no-unused-vars': 'error',
    'no-params-reassign': ['off'],
    indent: ['error', 2],
    'prettier/prettier': [
      2,
      {
        $schema: 'http://json.schemastore.org/prettierrc',
        printWidth: 80,
        tabWidth: 2,
        useTabs: true,
        semi: true,
        singleQuote: true,
        trailingComma: 'all',
        endOfLine: 'lf',
      },
    ],
  },
};
