service: serverless-graphql
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/index.handler
    events:
      - http:
          path: playground
          method: get